version: 2
jobs:
  build:
    docker:
      - image: devcafe/cmake-cookbook_circleci_ubuntu16.04-intel2018.1
        user: root
    steps:
      - checkout
      - run:
          shell: /bin/bash
          name: Set up Intel env vars
          command: |
            #whoami
            #echo 'export HATE="I HATE YOU"' >> $BASH_ENV
            #source $BASH_ENV
            #echo $HATE
            #ls -lhtr /opt/intel/bin
            #which source
            #echo $HATE
            source /opt/intel/bin/compilervars.sh -arch intel64 -platform linux
            echo $MKLROOT
