version: 2
jobs:
  build:
    docker:
      - image: robertodr/fuffa
        #entrypoint:
        #  - /opt/docker/bin/entrypoint
        command: ["/opt/docker/bin/entrypoint"]
    steps:
      - checkout
      - run: echo "A first hello from $PATH"
      - run: python3 --version
