version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
        #entrypoint:
        #  - "echo Hellllllllloooooo"
        #command: ["/bin/bash"]
    steps:
      - checkout
      - run: echo "A first hello from $PATH"
