version: 2
jobs:
  build:
    docker:
      - image: robertodr/fuffa
        entrypoint:
          - /opt/docker/bin/entrypoint
        #command: ["/bin/bash", "-c", "echo stocazzo"]
    steps:
      - checkout
      - run: echo "A first hello from $PATH"
      - run: python3 --version
