version: 2
jobs:
  build:
    docker:
      - image: devcafe/cmake-cookbook_ubuntu16.04-intel2018.1
        entrypoint:
          - /opt/docker/bin/entrypoint
        command: [ "/bin/bash" ]
    steps:
      - checkout
      - run: echo "A first hello from $USER"
      - run:
          name: Python dependencies
          command: |
            pip install --user pipenv --upgrade pip
            pipenv install --three
      - run:
          name: Report
          command: |
            pipenv run python --version
