version: 2
jobs:
  build:
    docker:
      - image: devcafe/cmake-cookbook_circleci_ubuntu16.04-intel2018.1
    steps:
      - checkout
      - run:
          name: Set up Intel env vars
          command: |
            echo 'export HATE="I HATE YOU"' >> $BASH_ENV
            #echo 'source /opt/intel/bin/compilervars.sh -arch intel64 -platform linux' >> $BASH_ENV
            source $BASH_ENV
            echo $HATE
            #echo $MKLROOT
