version: 2
jobs:
  build:
    docker:
      - image: devcafe/cmake-cookbook_circleci_ubuntu16.04-intel2018.1
    steps:
      - checkout
      - run:
          name: Well
          command: |
            echo "A first hello from $PATH"
            pipenv
