version: 2
jobs:
  build:
    docker:
      - image: devcafe/cmake-cookbook_circleci_ubuntu16.04-pgi17.4
        user: root
    steps:
      - checkout
      - run:
          name: A little check
          command: |
            which pgfortran
            which pgcc
            which pgc++
