version: 2
jobs:
  build:
    docker:
      - image: robertodr/fuffa
    steps:
      - checkout
      - run:
          name: Well
          command: |
            echo "A first hello from $PATH"
            python3 --version
            pip3 install pipenv
            pipenv help
